### ISSUE TITLE
DESCRIBE queries not working 

### ISSUE THREAD

**Issue by keski** [tenforce/docker-virtuoso#1]
The current build produces an error when executing DESCRIBE queries.

**Comment by erikap** [comment]
I executed a simple DESCRIBE query in the docker and it worked for me. What is the exact query you are trying to execute @keski?
The dockerization shouldn't have an impact on Virtuoso's query functionality so it will probably be a bug in the query or in Virtuoso.

**Comment by keski** [comment]
It's interesting that it works for you. The query was not the issue since an error was generated in all cases. When sql:describe-mode is set manually it works:
```
SQL>SPARQL
define sql:describe-mode "SPO"
DESCRIBE <http://example.org#Pizza>
```
I traced the issue to the Virtuoso build version, but if it worked for you perhaps its related to something else.

See also:https://github.com/openphacts/ops-platform-setup/issues/10

**Comment by madnificent** [comment]
Closing this issue as openphacts/ops-platform-setup#10 describes the way content is dumped and loaded.  It seems that either upstream Virtuoso or the dump files are incompatible with this dockerized version of Virtuoso.

@keski Please reopen this issue if neither upstream nor the dump format seems to cause this behaviour.  I'm monitoring openphacts/ops-platform-setup#10 in case something pops up.
