### ISSUE TITLE
Can't set ini keys with underscores via environment variables

### ISSUE THREAD

**Issue by jvstein** [tenforce/docker-virtuoso#17]
The grep/sed commands used in [virtuoso.sh](https://github.com/tenforce/docker-virtuoso/blob/master/virtuoso.sh#L28) make it impossible to set the following parameters.

```ini
[Flags]
tn_max_memory=2000000000
hash_join_enable=2
```

If you try to do it like this:
```shell
VIRT_Flags_tn_max_memory=2000000000
VIRT_Flags_hash_join_enable=2
```

The resulting virtuoso.ini looks like this:
```ini
[Flags]
memory=2000000000
enable=2
```

**Comment by nvdk** [comment]
I've merged your PR and it should be available on tenforce/virtuoso:latest soon. I'll add specific releases later today.
