### ISSUE TITLE
Error loading DBPedia Turtle in Virtuoso

### ISSUE THREAD

**Issue by staticdev** [tenforce/docker-virtuoso#25]
Hi!

I downloaded DBPedia turtle-files with their extraction framework (https://github.com/dbpedia/extraction-framework).

Then I used the docker image tenforce/virtuoso:1.3.2-virtuoso7.2.2 after exctracting all ttl.bz2 to a toLoad file.

After the full load, I checked isql with select * from DB.DBA.LOAD_LIST; and got an error from one of the files:

    2 2019.2.2 11:31.43 69876000 2019.2.2 11:31.44 521623000 0 NULL 37000 [Vectorized Turtle loader] SP029: TURTLE RDF loader, line 172395: syntax error

The virtuoso endpoint (http://localhost:8890/sparql) is online, but the queries don't return correct results.

Do you know what I can do to correct this error?

**Comment by TallTed** [comment]
I would start by using `tenforce/virtuoso:latest` or `tenforce/virtuoso: virtuoso7.2.5` or `tenforce/virtuoso:1.3.2-virtuoso7.2.5`, all of which should be based on Virtuoso 7.2.5.1 (from August 2018), rather than the rather elderly `tenforce/virtuoso:1.3.2-virtuoso7.2.2` which is based on the similarly elderly Virtuoso 7.2.2 (from December 2015).

**Comment by staticdev** [comment]
Double sorry, I am using tenforce/virtuoso:1.3.2-virtuoso7.2.5.1 now and same problem.

You can close this issue if you want. And we make the problem/solution public on StackOverflow.

**Comment by TallTed** [comment]
Next would be to try with the latest [OpenLink official docker image, `openlink/virtuoso-opensource-7`](https://hub.docker.com/r/openlink/virtuoso-opensource-7), which is based on Virtuoso 7.2.6-rc1 (from December 2018).  If issues still persist, I suggest you come to the (also public, but more focused) [OpenLink Community Forum](https://community.openlinksw.com) where we can work more directly with you.

**Comment by TallTed** [comment]
@StaticX

> same problem with the same line using virtuoso-opensource-7. I think there might be something wrong with this turtle file extracted.

Yes. I notice you said you extracted "all ttl.bz2 to a toLoad file" -- is that one giant TTL file? If so, I'd like to see the 10 or so lines around 172395 (so, 172390-172400). 

Also note that generally speaking, you'll be better off loading a bunch of smaller files with our [bulk-load tool](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader), which would also help narrow the issue (and so, help with getting the original fixed).

**Comment by TallTed** [comment]
>>> I am sorry, it was just a writing mistake (updated). Where you read "file" is "folder". There is one TTL for each `ttl.bz2` in the `toLoad` folder.
>>
>> OK, so I'd like to see those lines from that file (it shouldn't need to be the whole file), either added to your question within a code-fence here, or attached to your question on the other site.
>
> Updated with the line. I don't see any difference with this line in specific.
>
> Line 172395 of that file seems ok: 
>
>       <http://pt.dbpedia.org/resource/Reino_de_Roma> <http://dbpedia.org/ontology/governmentType> <http://pt.dbpedia.org/resource/Monarquia> <http://pt.wikipedia.org/wiki/Reino_de_Roma?oldid=53119289&ns=0> .

Well, it's not valid Turtle, which only has 3 elements per line (Subject, Predicate, Object). That might be a line of N-Quad serialization.

**Comment by TallTed** [comment]
> that is a bit strange, since the complete file has this structure. And there is no error on the previous lines. Another line example: 
>
>     <pt.dbpedia.org/resource/Afeganistão> <dbpedia.org/ontology/officialLanguage> <pt.dbpedia.org/resource/Língua_dari> .

Note that your new example has *three* elements (the strings wrapped in angle-brackets) on the line.

To make these a bit easier to parse visually, I'm going to remove all but the last bit of each string, and stack the two lines in a code-block (which you should view without line wrapping) --

    <...Reino_de_Roma> <...governmentType>   <...Monarquia>    <...Reino_de_Roma?oldid=53119289&ns=0> .
    <...Afeganistão>   <...officialLanguage> <...Língua_dari> .

**Comment by TallTed** [comment]
> I see.. there might be a problem with my dbpedia extraction then.

Depending on your project, you might consider [loading and working from the DBpedia dumps](https://wiki.dbpedia.org/develop/datasets)...

**Comment by staticdev** [comment]
After extracting DBPedia with https://github.com/dbpedia/extraction-framework, I had to run this script:

https://github.com/dbpedia/databus-maven-plugin/blob/master/dbpedia/rapandsort.sh

Then I put it in the toLoad folder (all the ttl files) and it worked! This issue can also be closed.
