### ISSUE TITLE
Remove VOLUME from Dockerfile

### ISSUE THREAD

**Issue by GrazingScientist** [tenforce/docker-virtuoso#31]
Thank you for providing this image.

Lately, I ran into the situation where I was wondering why there are so many anonymous Docker volumes on my server. Then I found that your image has a `VOLUME /data` instruction, which I find completely unnecessary. If I want to mount `/data` then I create a volume when I call `docker run` or `docker-compose run`.

Could you please remove this instruction?

Cheers,

Adrian

**Comment by claudiu-cristea** [comment]
Agree with @GrazingScientist

**Comment by TallTed** [comment]
@claudiu-cristea @GrazingScientist 

You may want to take a look at [the docker images](https://hub.docker.com/u/openlink) maintained directly by [OpenLink Software](https://www.openlinksw.com/), the vendor behind [Virtuoso](https://virtuoso.openlinksw.com/) itself.

Of particular interest, the [OpenLink Virtuoso Open Source Edition 7.2 Docker Image](https://hub.docker.com/r/openlink/virtuoso-opensource-7/).

**Comment by GrazingScientist** [comment]
I also just recently stumbled across the official image. Thanks, @TallTed

**Comment by claudiu-cristea** [comment]
@TallTed, thank you. Unfortunately, it seems that they are not publishing the image code (Dockerfile, etc)

**Comment by claudiu-cristea** [comment]
@TallTed  @GrazingScientist I've managed to reverse the image to Dockerfile and looks like they are also defining a volume
