### ISSUE TITLE
Enabling Cross-Origin Resource Sharing (CORS) in Dockerfile?

### ISSUE THREAD

**Issue by KonradHoeffner** [tenforce/docker-virtuoso#35]
[According to the Wiki](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksCORsEnableSPARQLURLs), one can enable CORS in the conductor web interface, but I want to enable that by default in a Docker image based on this one. Is it possible to configure this container in that way and if yes, how?

**Comment by TallTed** [comment]
The [guidance I just provided](https://github.com/tenforce/docker-virtuoso/issues/34#issuecomment-961195528) in your other issue (#34) is applicable to this as well.

**Comment by langens-jonathan** [comment]
Hey Konrad, Openlink has provided a great guide on how to enable CORS: http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksCORsEnableSPARQLURLs. I believe you can also do it through a isql statement. So that could be added in a custom image with a separate RUN command.

**Comment by KonradHoeffner** [comment]
@langens-jonathan Hello Jonathan, thanks for the link, however that is the same one as posted at the top, which shows how to do it using a graphical user interface but not how to do it using ISQL.

**Comment by KonradHoeffner** [comment]
@TallTed: Thank you for the guidance, I will implement that!

**Comment by nvdk** [comment]
@KonradHoeffner, fyi in our fork you can enable the CORS setting with a env flag if you want: https://github.com/redpencilio/docker-virtuoso/ . I think it should be fairly trivial to extract and create a PR to the tenforce image if you have the time.

**Comment by KonradHoeffner** [comment]
@nvdk: Thanks! Just executing ` update DB.DBA.HTTP_PATH set HP_OPTIONS = serialize(vector('browse_sheet', '', 'noinherit', 'yes', 'cors', '*', 'cors_restricted', 0))  where HP_LPATH = '/sparql';` in the setup SQL script worked!
