### ISSUE TITLE
VIRT_Parameters_DirsAllowed does not affect init

### ISSUE THREAD

**Issue by mkarikom** [tenforce/docker-virtuoso#39]
I set up the environment in the docker-compose.yml to add the directory `/tmp` to DirsAllowed like:
```
        environment:
            - VIRT_Parameters_DirsAllowed="., ../vad, /usr/share/proj, /tmp"
```

Once the container is running I can log in and see that docker-compose ran as expected:
```
root@eeb0cfd5a23c:/opt/virtuoso-opensource/database# echo $VIRT_Parameters_DirsAllowed
"., ../vad, /usr/share/proj, /tmp"
```

However, when I log into conductor, the DirsAllowed parameter is unchanged:
[imgur screenshot](https://imgur.com/a/O9dXiEU)

**Comment by TallTed** [comment]
You might try with OpenLink Software's [official VOS7 docker image](https://hub.docker.com/r/openlink/virtuoso-opensource-7/)...

**Comment by mkarikom** [comment]
Ok thanks [this worked](https://community.openlinksw.com/t/how-to-bulk-load-data-into-a-virtuoso-docker-instance/3248#the-10-bulkloadsql-script-9)

**Comment by TallTed** [comment]
@mkarikom — Please close this issue, if it's been resolved to your satisfaction.
