### ISSUE TITLE
Please update Docker hub

### ISSUE THREAD

**Issue by mhoangvslev** [tenforce/docker-virtuoso#40]
Could you please update Docker Hub repo with latest versions?

**Comment by TallTed** [comment]
You might consider trying the Docker images [maintained by OpenLink Software](https://hub.docker.com/r/openlink/), who also produce [Virtuoso](https://virtuoso.openlinksw.com/) itself....

**Comment by mhoangvslev** [comment]
Before opting for this option, I would like to know if it's possible to continue using this repo. On their repo, I notice some change in the configfile but Idk if there are other stuff.

**Comment by nvdk** [comment]
@mhoangvslev  a bit late to the party, but another option you could consider is our fork at https://github.com/redpencilio/docker-virtuoso

**Comment by TallTed** [comment]
@mhoangvslev 
> On their repo, I notice some change in the configfile but Idk if there are other stuff.

What changes did you notice? Differences are not always intentional... and even if they were intentional, they may not be advisable.

**Comment by TallTed** [comment]
@nvdk 
> another option you could consider is our fork at https://github.com/redpencilio/docker-virtuoso

What makes your fork different/better? The redpencilio fork appears to be based on the tenforce fork, which is based on (but has been lagging behind for 2 years, most recently updated for 7.2.6.1!) OpenLink's own, original fork, updated to 7.2.9 in February.

**Comment by mhoangvslev** [comment]
@nvdk I appreciated your offer but I think @TallTed is right. Most people will stick to the official image anyway for security and maintenance reasons.

**Comment by nvdk** [comment]
@TallTed just FYI (and you would have noticed had you actually checked), the redpencil fork was on 7.2.8 and just today moved to 7.2.9. We don't trail all that far from the official virtuoso version. 

As to what it adds over the openlink one: 
- An opensource Dockerfile that can easily be forked and extended
- some scripts to make backups etc easier. 
- An extensive readme on how to use the docker image.
